### ISSUE TITLE
Add the black formatter GitHub Action

### ISSUE THREAD

**Issue by AnjumanHasan** [Mr-Sunglasses/pastebin-telegram#14]
# Add the black formatter GitHub Action 

## Overview
Currently, there is no Code Formatter used in pastebin-telegram, Our Goal is to add a Black code formattingr in pastebin-telegram.

## Description
Describe the solution you'd like -  Add a GitHub action that checks a PR for coding style using [black](https://pypi.org/project/black/). The GHA should be able to format the code and commit it to the PR if the PR is not following the coding style.

## Expected outcomes

A uniform coding style across pastebin-telegram, that Autoformat code on every PR.

## Skills

GitHub Actions, Python

## Possible mentors
[Kanishk Pachauri](https://github.com/Mr-Sunglasses), [Anjuman Hassan](https://github.com/AnjumanHasan)

## Expected project size

50 hours.

## Difficulty

Hard.

**Comment by Srijan-SS02** [comment]
#Add the black formatter GitHub Action

My Background and Technical Skills
I have been into coding stuff since class 8th trying my hands on Python and its libraries like Pandas etc. Right now i'm handy with WebD, Python, C++ and in designing I have worked on Figma. And also I have solved similar problem of adding black formatter.

What problem are you trying to solve and Your Approach?

So I am trying to add the black formatter through github action. Black formatter is python libraries which auto formats the code like indentation and other things. Which ultimately saves user time who will push there messy code.
I have also created a sample github action in one of my repo which uses super-Linter to check format of code.
link to it : https://github.com/Srijan-SS02/ActionDemo

Your Timeline to solve the problem.

12th Sep 2022 : get the project assigned by Mentors and try to interact with mentors
13th Sep 2022 : trying to solve the issue and trying to get helped by the mentors
14th Sep 2022 : wrapping up the issue and fixing the minor bugs if any

@Mr-Sunglasses @AnjumanHasan tagging maintainers for better reach

**Comment by Mr-Sunglasses** [comment]
Hey @Srijan-SS02 I have assigned you to this issue.

**Comment by AnjumanHasan** [comment]
@Mr-Sunglasses Closing this Issue. As PR #19 Solves this. Thanks @Srijan-SS02 for your valuable contribution.
