### ISSUE TITLE
Add a Feature to Download All the Post of A Public Instagram Profile.

### ISSUE THREAD

**Issue by AnjumanHasan** [Mr-Sunglasses/pastebin-telegram#16]
# Add a Feature to Download All the Post of A Public Instagram Profile.

## Overview
Add a Feature to Download All the Post of A Public Instagram Profile and Send it to the User.

## Description
The Goal is to Create a Feature in pastebin-telegram bot to download all the Post specifically images to the server and send it to the user afterwards, Use threading to Download Photos concurrently at the same time.

## Expected outcomes

Feature of downloading all Post images of a specific user from Instagram using Pastebin-telegram.
## Skills

Python, Threading, Api's.

## Possible mentors
[Kanishk Pachauri](https://github.com/Mr-Sunglasses), [Anjuman Hassan](https://github.com/AnjumanHasan)

## Expected project size

100 hours.

## Difficulty

Hard.

**Comment by devAyushDubey** [comment]
I would like to work on this.

**Comment by Mr-Sunglasses** [comment]
Thanks, @devAyushDubey [Ref to this File](https://github.com/Mr-Sunglasses/pastebin-telegram/blob/insta-profile-download/pastebin-bot/insta_all_pictures.py) I have added this feature previously in the bot but the problem is the image downloading takes a lot of time. The main goal is to use multiple threads to make the process fast. Ref to these videos [Video-1](https://www.youtube.com/watch?v=cstTD6jPHrc) [Video-2](https://www.youtube.com/watch?v=2MGAVyLNx44) to learn how to optimize image downloading using threads.

**Comment by Mr-Sunglasses** [comment]
I am looking forward to your response and PR. If you need any help just tag me in this issue.
